# Figure 15.11 - Service Log File Output
# Chapter 15: PowerShell Studio and Windows Services
# PowerShell Advanced Cookbook - BPB Publications
#
# Platform: Windows
# Prerequisites: WeatherLogService running
#
# This figure shows the JSON log file output generated by the service.
#
# ============================================================================
# LOG FILE OUTPUT FORMAT
# ============================================================================
#
# The WeatherLogService writes JSON log entries (one per line):
#
# File: C:\Temp\WeatherLog.json
#
# {"timestamp":"12-01-2024 10:00:00,123","message":"The weather in Aarhus is clear sky with a temperature of 5.23 Celsius that feels like 2.15 Celsius","level":"INFO"}
# {"timestamp":"12-01-2024 10:01:00,456","message":"The weather in Aarhus is clear sky with a temperature of 5.25 Celsius that feels like 2.18 Celsius","level":"INFO"}
# {"timestamp":"12-01-2024 10:02:00,789","message":"The weather in Aarhus is few clouds with a temperature of 5.30 Celsius that feels like 2.22 Celsius","level":"INFO"}
#
# JSON Structure:
# {
#     "timestamp": "dd-MM-yyyy HH:mm:ss,fff",
#     "message":   "Weather description string",
#     "level":     "INFO|WARNING|ERROR|CRITICAL|DEBUG|OK"
# }
#
# This format is optimized for:
# - Datadog log ingestion
# - SIEM tools
# - Log aggregation platforms
# - Easy parsing with ConvertFrom-Json

# No executable code - this is output from the service

